name: run_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  hive_ce: ^2.5.0+2
  hive_ce_flutter: 2.0.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.0

dev_dependencies:
  build_runner: ^2.4.13
  hive_ce_generator: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
