// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:run_planner/core/models/distance_type.dart';
import 'package:run_planner/core/models/hills_run.dart';
import 'package:run_planner/core/models/interval_run.dart';
import 'package:run_planner/core/models/plan_type.dart';
import 'package:run_planner/core/models/run.dart';
import 'package:run_planner/core/models/run_type.dart';
import 'package:run_planner/core/models/run_week.dart';
import 'package:run_planner/core/models/tempo_run.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DistanceAdapter());
    registerAdapter(HillsRunAdapter());
    registerAdapter(IntervalRunAdapter());
    registerAdapter(PlanAdapter());
    registerAdapter(RunAdapter());
    registerAdapter(RunTypeAdapter());
    registerAdapter(RunWeekAdapter());
    registerAdapter(TempoRunAdapter());
  }
}
